Add support for zhimi.heater.za2
rytilahti/python-miio pull request #1301
Opened 2022-01-16 14:44 UTC by PRO-2684

This PR adds support to zhimi.heater.za2.
`heater_miot_za2.py`'s code is modified from `heater_miot.py`. Compared to already supported mc2 model, za2 can monitor relative humidity, so I added `relative_humidity` function.
P.S. Comment is wrong at `heater_miot.py`, line 21. Should be `# Physical Control Locked (siid=5)`.

2022-01-16 16:51 UTC, rytilahti commented
Please just extend the existing implementation as they are from the same manufacturer and they do not differ that much. You can do that by basing your PR on top of #1302, and introducing `_mappings` that is a dict containing model-keyed mappings. The correct mapping will then be chosen automatically run-time :-)

For the extra `relative_humidity`, you can check if the value is there and mark it as `Optional` in the container to keep the API for both types of models:
```
    @property
    def relative_humidity(self) -> int:
        """Current relative humidity."""
        return self.data.get("relative_humidity")
```

2022-01-17 02:50 UTC, PRO-2684 commented
On za2, `LedBrightness` 0 means "On (Bright)", 1 means "On (Dim)", 2 means "Off". How should this conflict be solved?

2022-01-18 00:55 UTC, PRO-2684 commented
@rytilahti This should work now. But as I modified the class `LedBrightness`, users may encounter compatibility issues.

2022-01-19 19:02 UTC, rytilahti requested changes
Just two more things and this is good to go!

2022-01-19 19:02 UTC, rytilahti commented on miio/heater_miot.py
> +    0 = On (Bright), 1 = On (Dim), 2 = Off
This is confusing API-wise.. How about just adding a `Dim = 2` to the original enum, and performing the conversion per-model basis (and warn about unsupported `Dim` for mc2?

2022-01-19 19:02 UTC, rytilahti commented on miio/heater_miot.py
> +    def relative_humidity(self) -> Union[int, None]:
```suggestion
    def relative_humidity(self) -> Optional[int]:
```

2022-01-20 02:15 UTC, PRO-2684 commented
I've run the tests and it shall be fine now.

2022-01-20 19:33 UTC, rytilahti approved these changes
Please fix the tests and update README.md, and then this is good to go! :tada:

2022-01-21 01:44 UTC, rytilahti commented
Oh, looks like the tests are still failing. Btw, you can also run the tests locally using executing `pytest` or `tox` :-)

2022-01-21 03:53 UTC, PRO-2684 commented
The reason why the tests are not passed is that the dummy test cases are based on mc2, but I chose to fall back on the strictest restriction in times of unrecognized models, including dummy.

2022-01-22 15:30 UTC, rytilahti commented
This is good to go, thanks @PRO-2684!

2022-01-22 15:31 UTC, merged