Don't log error message when decoding valid discovery packets (#1824).
rytilahti/python-miio pull request #1832
Opened 2023-09-24 17:54 UTC by gunjambi

Fix `Unable to decrypt, returning raw bytes` warning message when decoding Discovery messages. Fixes #1824

I opted for a quick surgical fix here rather than rework the whole message parsing. While separating the Discovery messages from normal data messages is quite easy in the context of miioprotocol, there's a quite bit of uses of the `Message` in other places too. I didn't feel confident in changing those.

Additionally, it doesn't even seem desirable to separate Discovery-Ack and Data messages. It seems useful in some cases to be able to parse any message without knowing ahead of time what kind of data it might contain. (I doesn't really matter right now as the token, i.e. decryption key, must be supplied ahead of time, but it is conceivable that a parser might first match the ID of the reply to the request and then parse the contents. )

2023-10-04 23:25 UTC, rytilahti requested changes
A couple of simple changes and this is good to go, thanks! :+1:

2023-10-04 23:25 UTC, rytilahti commented on miio/protocol.py
> +        # anyway.
```suggestion
        # Missing payload is expected for discovery messages.
```
let's keep it simple here, also, there are some (very) old devices that actually respond with a valid token :-)

2023-10-07 12:25 UTC, gunjambi commented
Proposed changes applied.

2023-10-07 18:54 UTC, rytilahti approved these changes
Great, thanks again! :+1:

2023-10-07 18:54 UTC, merged